### ISSUE TITLE
Hi, https://github.com/thunks/thunks do some more than bach

### ISSUE THREAD

**Issue by zensh** [phated/bach#11]
https://github.com/thunks/thunks
https://github.com/thunks/thunk-stream

**Comment by phated** [comment]
That is a very cool library!  I don't think it works for the use-case that `bach` was created for.  `bach` was built on top of `now-and-later` which is like `async.map` but with extension points.  We use those extension points in `undertaker` to track the amount of time each execution takes.  We then use those in gulp to report times of task execution to the end user.

I will definitely be keeping an eye out on thunk though. Thanks

**Comment by zensh** [comment]
:100:
