### ISSUE TITLE
series returns too soon if sync function is first

### ISSUE THREAD

**Issue by doowb** [phated/bach#14]
If you have a `sync` function and an `async` function, and pass the `sync` function to `.series` first, then execution finishes before the `async` function is finished:

```js
var bach = require('bach');
function sync () {
  console.log('sync function');
}

function async (done) {
  console.log('async function');
  done(null, 'async done');
}

var fn = bach.series(sync, async);
fn(function (err, msg) {
  console.log(msg);
});
```

This could be handled in `async-done` by checking the function length (like was done in orchestrator), but I don't know if that's how you're intending `async-done` to be used, so I opened the issue here.

**Comment by phated** [comment]
Sync tasks are completely unsupported (and removed from gulp 4.0).  Always pass the `done` callback and call it, even in sync functions.  Execution doesn't finish, node exits because you have no more work to do in the event loop.

**Comment by doowb** [comment]
Thanks for the explanation. For some reason, I didn't realize that sync was unsupported.
